"""`GeneratePodcastScript` — the RLM task behind the Audio Overview (`rlm-notebook audio`).

Same citation-grounded `RLMTask` pattern as `AnswerQuestion`/the Notebook Guide tasks: two input
fields (`sources` and, since invariant 39, `output_language`), one output field
(`script: PodcastScript`), sharing `instructions.py`'s citation-marker and validate-before-submit
The craft rules — tension, pacing, the reveal — live in the `podcast-craft` skill; they were never
in this prompt, and the skill is new material rather than an extraction (see `apply_skills` for the
split, and CLAUDE.md invariant 65 for why almost nothing moved). What IS in both is a must-apply rule
whose reason is long: the prompt states it, the skill explains it. That file also records a MISATTRIBUTION worth not repeating: an earlier version of it
justified the no-disfluencies rule with "not generated by the LLM in the transcript, but built into
the audio model", attributed to the NotebookLM team. That sentence is their hosts' editorial show
note, and the guest contradicts it when asked directly ("It's a bit of both ... in generating the
text, we also have to sort of give signals"). It reached this codebase from a fetched summary that
nobody opened the transcript to check — the same failure mode invariant 43 already records for three
TTS recommendations. The RULE survives on this project's own measurement instead: a Chinese sentence
with six characters of written filler synthesized to 4.08s against the plain sentence's 2.90s, i.e.
the filler was pronounced, not realised as prosody.

NOTE for whoever edits `_INSTRUCTIONS` below: a FIGURE OF SPEECH in a prompt becomes a factual
claim in the output. This one said an opening should explain why the sources are "worth half an
hour of someone's attention"; a real episode duly opened by asking the listener why it was worth
half an hour of their time, and then ran for three minutes. The rule that replaced it forbids
stating a duration at all — and the offending phrase is quoted HERE rather than in the prompt,
because quoting it there would hand the model the number again.

rules. Audio synthesis itself (`tts.py`) runs entirely AFTER this task returns, on its
already-SCHEMA-VALIDATED output — this module produces text only. (Not "already citation-checked":
nothing gates synthesis on verification, and an independent audit flagged the stronger phrasing as
exactly the kind of upgrade invariant 5 forbids. Citations are computed for DISPLAY alongside the
transcript.)
"""

from __future__ import annotations

from .instructions import (
    ACCUMULATE_LARGE_OUTPUTS,
    CITATION_RULES,
    GroundedTask,
    artifact_language_rule,
    validate_before_submit_rule,
)
from .schema import PodcastScript

__all__ = ["GeneratePodcastScript"]

_INSTRUCTIONS = f"""\
You are writing the script for a two-host PODCAST episode that discusses the
sources in this notebook — the kind of natural, conversational back-and-forth two people have when
one is explaining something interesting to the other, NOT alternating monologues or a dry
recitation of facts. Ground EVERY substantive claim ONLY in the `sources` text given to you as a
REPL variable — never your own background knowledge. If the sources don't support a claim, leave
it out rather than filling the gap from what you already know.

There are exactly two speakers, `host_a` and `host_b` — do not invent a third, and do not let one
host dominate; a good episode has both contributing roughly evenly, asking each other questions,
reacting, and building on what the other just said.

`target_length` says how long the episode should aim to be. It is a real target, not a hint:

- `short` — roughly 3 to 5 minutes: about 12 to 18 turns. One thread, followed properly. Say what
  the sources are, cover the single most important thing in them, and land it.
- `default` — roughly 8 to 12 minutes: about 30 to 45 turns. Room for three or four distinct
  threads, each developed rather than mentioned.
- `long` — roughly 18 to 25 minutes: about 60 to 90 turns. Enough to work through the sources
  properly: where they disagree, the reasoning behind a claim, an implication followed to the end.

A `default` or `long` script does NOT fit in one reply — accumulate `utterances` across REPL turns
as described below. Writing all 60-90 of them into a single code block is the one way this task
reliably fails.

Reach the target with SUBSTANCE, never with filler — no restating what was just said, no "that's
fascinating", no summarising the episode back to the listener mid-way. If the sources genuinely do
not hold enough to fill the target, stop short and say so briefly rather than padding: a short
honest episode is better than a long empty one. If they hold far more, select — do not try to cover
every detail at the cost of a conversation.

Do NOT write disfluencies or stage directions — no "um", no "呃", no "(laughs)", no "[pause]".
`Utterance.text` is both the transcript a reader sees and the string a text-to-speech voice reads,
and these voices read it literally: a written "um" is printed on screen AND pronounced as a word.
The skill catalog above has the measurement behind this, and what the products that do this well
actually do differently.

Give the episode a SHAPE. It has three parts, and the last one is the one most easily forgotten:

1. An opening that says what these sources are and why they are worth listening to — one or two
   turns, not a formal preamble. Never state or imply how long the episode runs: you cannot know
   that, and a guess becomes a factual claim the moment it is spoken. If a host names the format at
   all, the word is "podcast" — never a product or feature name.
2. The body: the substance, in whatever order makes the conversation work. Follow the interesting
   thread rather than the order the sources happen to be in.
3. A CLOSE. Do not simply stop when you run out of facts. Land it: one host briefly draws the
   threads together, and then the two of them say what it adds up to — the implication, the tension
   that is still unresolved, the thing that changed how they see it. Leaving the listener with a
   real open QUESTION is a good close — one the sources raise and do not settle. Ground that
   reflection in what the sources actually support; "what this makes me wonder" is honest,
   inventing a finding is not.
   An episode that ends mid-fact feels broken even when every fact in it was right.

**Write to be SPOKEN, but keep a name as its source wrote it.** This script is read aloud AND read
on screen, and the same `Utterance.text` is both — so a proper noun, a product, a standard or an
identifier stays in its original form (`Voyager 1`, `NASA`, `CVE-2026-1234`), not transliterated
into your own language. The transcript is what a listener falls back on when a word does not come
through clearly, and a rewritten name is exactly the word they cannot look up.

Numbers, dates and units DO get written the way they are spoken rather than the way they are
printed — those read aloud badly in every language and nobody needs to look them up. (A
`Citation`'s `quote` is verbatim regardless: it is evidence a reader checks against the source.)

{artifact_language_rule("the language named by the `output_language` variable")}

A `[[SRC:...]]` marker is NOT a citation and writing one into a host's line is not citing. It is
a coordinate for the interface; the reader never sees it, the VOICE READS IT ALOUD, and the passage
it pointed at is lost. A real run wrote 20 of them across 19 of its 47 utterances and filled in ZERO
`Citation` objects, so the episode said "S R C S one" out loud and arrived with no references. Put the
coordinate in a `Citation` on the utterance that makes the claim; write the line as a line.

{CITATION_RULES}

{ACCUMULATE_LARGE_OUTPUTS}

{validate_before_submit_rule("validate_podcastscript")}
"""


class GeneratePodcastScript(GroundedTask):
    """Generate a two-host podcast script grounded in a notebook's sources, with citations."""

    signature = (
        "sources: str, output_language: str, target_length: str -> script: PodcastScript"
    )
    output_field = "script"
    output_model = PodcastScript
    instructions = _INSTRUCTIONS
